#gem 'rich', git: 'https://github.com/a-ono/rich.git'
#gem 'kaminari'
#gem 'htmlentities'
# gem 'paperclip', '~> 4.2.1'
#gem 'pandoc-ruby'
source 'https://rubygems.org'
# It is needed for upgrading CKEditor
#gem 'sprockets-rails', '< 3.0.0' 
gem 'rich', git: 'https://github.com/a-ono/rich.git'
gem 'kaminari'
gem 'htmlentities'
gem 'paperclip', '~> 6.1.0'  # Updated for Rails 5.2 compatibility (last version with Rails 5 support)
gem 'pandoc-ruby'

# It is needed for upgrading CKEditor
#gem 'sprockets-rails', '< 3.0.0'
